spring:
  datasource:
    url: jdbc:mysql://localhost:3344/university
    username: "root"
    password: "password"


  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
server:
  port: 8082
